actions/compare.js, actions/transactions.js
Minor improvements of xpub<>address comparison feature.
=> refactor(comparison): add checks, clean code

package-lock.json, package.json
Fix errors and warnings related to some dependencies.
=> fix(package.*): dateformat dependency error and misc. warnings

.gitignore, README.md, src/actions/checkAddress.ts, src/actions/checkBalance.ts, src/actions/importOperations.ts, src/actions/processTransactions.ts, src/actions/saveAnalysis.ts, src/api/customProvider.ts, src/api/defaultProvider.ts, src/display.ts, src/helpers.ts, src/models/address.ts, src/models/comparison.ts, src/models/operation.ts, src/scan.ts, src/settings.ts
Implements `--save` option allowing to save the analysis as a JSON file.
`$ node build/scan.js <xpub> [--import <filepath>] --save <directory>`
=> Save as json

README.md, src/actions/checkBalance.ts, src/actions/importOperations.ts, src/display.ts, src/helpers.ts, src/scan.ts, src/settings.ts
Distinction between two options:
- `--quiet`: no progress: each address is only displayed once (no `analyzing...`)
- `--silent`: addresses and results are not displayed
=> feat(display): quiet v. silent options

.dockerignore, .gitignore, .prettierignore, Dockerfile, README.md, package.json, src/scan.ts, tsconfig.json
- refactor Dockerfile for faster rebuilds
- update package.json name field (`@ledgerhq/xpub-scan`) to prepare publish
- `build` -> `lib` by convention
- signal handling in entrypoint, to make process quit on SIGINT/SIGTERM
=> VPE-100 Refactor Dockerfile, prepare npm module

README.md, package.json, src/actions/saveAnalysis.ts, src/scan.ts
- prettier fix
- put `scan.js` as "bin" entry in package.json, and properly fix mode of entry point
=> Finalize module preparation

package.json, yarn.lock
Fix Dependabot alert related to lodash.
=> fix(package.json): remove lodash

package.json, src/comparison/diffs.ts
Diffs:
- Improve output (`[ OK ]`, `[ KO ]`)
- Do not display aggregated ops as diffs
=> Diffs: Improve Output

__tests__/helpers.test.ts, __tests__/test-utils.ts, babel.config.js, jest.config.ts, package.json, src/helpers.ts, yarn.lock
for now it will default to 5 retries, with a `0` delay between retries.
Feel free to update those values by adding parameter to `getJSON` where you want
=> VPE-152 Implement `retry` helper & use it in `getJSON`

src/input/importOperations.ts
Fix issue related to the type C JSON imported **Ethereum** operations.
=> Fix ETH-Related Type C JSON Import

src/api/customProvider.ts, src/api/defaultProvider.ts, src/input/importOperations.ts
Use fixed-point notation (10 digits) to compare imported and actual Ethereum amounts.
=> Fix Value Representation of Ethereum amounts

README.md, __tests__/helpers.test.ts, package.json, src/actions/checkBalance.ts, src/actions/saveAnalysis.ts, src/api/customProvider.ts, src/api/defaultProvider.ts, src/comparison/compareOperations.ts, src/comparison/diffs.ts, src/configuration/settings.ts, src/display.ts, src/helpers.ts, src/input/args.ts, src/input/importOperations.ts, src/models/address.ts, src/models/operation.ts, src/models/stats.ts, src/modules.d.ts, src/scan.ts, yarn.lock
Use of BigNumber library for the internal representation of the numbers. 
This is the first step towards more robust amounts-related arithmetic operations.
=> Use of BigNumber Library

src/api/defaultProvider.ts, src/comparison/diffs.ts
Fix issue with the displaying of diff amount.
=> fix(BigNumber): diff amount

src/actions/saveAnalysis.ts, src/api/customProvider.ts, src/comparison/compareOperations.ts, src/configuration/settings.ts, src/display.ts, src/helpers.ts, src/input/importOperations.ts, src/models/operation.ts, src/templates/report.html.ts
**Main additions:**
- Import incoming Ethereum token transfers operations from JSON files type C and check them
- Import smart contract operations (not token transfers) from JSON files type C and check them using new `/internal` endpoint from CryptoAPIs
Note that, at this stage, the contents of the tokens transfers and smart contract operations in general are not verified (it depends on the full implementation of Smart Check).
See this example:
**Additional feature:**
- HTML reports now redirect to Etherscan (when clicking on an address or a transaction hash) when an Ethereum address has been analyzed
=> Ethereum: Incoming Tokens and Smart Contract Interactions

package.json, src/api/customProvider.ts, yarn.lock
Fixing an edge case related to Ethereum addresses.
When an Ethereum address has not associated standard transaction (i.e., non-ERC20 or internal transaction), the custom provider states that this address has no transaction overall. 
Therefore, ERC20-related transactions of Ethereum addresses with no standard transaction were ignored until this fix.
=> Fix Ethereum Edge Case

.github/workflows/regression_tests.yml, .github/workflows/regression_tests/check.py
Currently, only the custom provider is being tested by regression tests.
This update extends the regressions tests to the default provider.
=> Regression Tests: Test Default Provider

src/actions/saveAnalysis.ts, src/templates/report.html.ts
Related to this [ticket](https://ledgerhq.atlassian.net/browse/VG-3442), there is now a CSS pagination with a page size of 100 on the `addresses`/`utxos`/`transactions`/`comparisons`&`diffs` tables in the rendered html file.
https://user-images.githubusercontent.com/97895233/157280270-c6945e8f-dc53-4e38-9c02-5921fdd42426.mov
=> VG-3442 pagination

npm-shrinkwrap.json, package.json, src/input/importOperations.ts
Fix small bug related to files from Custom G (CSV)
=> Fix Custom G CSV Import

npm-shrinkwrap.json, package.json, src/actions/checkAddress.ts, src/actions/processTransactions.ts, src/actions/saveAnalysis.ts, src/api/customProvider.ts, src/api/defaultProvider.ts, src/configuration/settings.ts, src/scan.ts
Clarify the intent by:
- Adding comments
- Renaming some variables
- Slightly refactoring
=> Add Comments (2/n)

npm-shrinkwrap.json, src/actions/checkBalance.ts, src/actions/processTransactions.ts, src/actions/saveAnalysis.ts, src/api/customProvider.ts, src/api/defaultProvider.ts, src/comparison/compareOperations.ts, src/comparison/diffs.ts, src/display.ts, src/input/check.ts, src/input/importOperations.ts, src/models/address.ts, src/models/ownAddresses.ts, src/models/transaction.ts, src/types.ts
Clarify the intent by:
- Adding comments
- Renaming some variables
- Slightly refactoring
=> Add Comments (3/n)

src/comparison/compareOperations.ts
Clarify the intent by:
- Adding comments
- Slightly refactoring
=> Add comments (4/n)

npm-shrinkwrap.json, package.json, src/actions/deriveAddresses.ts, src/actions/scanner.ts, src/api/defaultProvider.ts, src/comparison/compareOperations.ts, src/helpers.ts, src/input/importOperations.ts, src/models/address.ts
Fix some of the issues detected by SonarQube
=> SonarQube: Fix Some Issues

.github/workflows/static_analysis.yml, __tests__/checkModels/address.test.ts, __tests__/checkModels/fakeRawTransactions.json, jest.config.ts, src/actions/checkBalance.ts, src/actions/deriveAddresses.ts, src/actions/processTransactions.ts, src/actions/saveAnalysis.ts, src/configuration/currencies.ts, src/helpers.ts, src/models/address.ts, src/models/ownAddresses.ts, src/models/stats.ts
- Fix some issues detected by SonarQube (continued)
- Improve code coverage (test `Address` model)
=> SonarQube: Fix Some Issues (Continued)
